// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Returns true if options exist for the current platform.
  static bool get isConfigured {
    try {
      currentPlatform;
      return true;
    } catch (_) {
      return false;
    }
  }

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4LhP8IZ_XtHD-iIPgTlB7y4ilgaJ1QnE',
    appId: '1:778603180925:web:0282137887e26ffd87d214',
    messagingSenderId: '778603180925',
    projectId: 'buddy-app-5aa31',
    authDomain: 'buddy-app-5aa31.firebaseapp.com',
    storageBucket: 'buddy-app-5aa31.firebasestorage.app',
    measurementId: 'G-D2309E5Q2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe5EORnK8NFo_mig6Zrr6PEoUwRqIurZc',
    appId: '1:778603180925:android:22a39eb537fbe87d87d214',
    messagingSenderId: '778603180925',
    projectId: 'buddy-app-5aa31',
    storageBucket: 'buddy-app-5aa31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQM3o1jtcYFzUSeapJ9DlVDJX7rCcsUsY',
    appId: '1:778603180925:ios:f9f7f311df0d15b387d214',
    messagingSenderId: '778603180925',
    projectId: 'buddy-app-5aa31',
    storageBucket: 'buddy-app-5aa31.firebasestorage.app',
    iosBundleId: 'com.example.buddyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQM3o1jtcYFzUSeapJ9DlVDJX7rCcsUsY',
    appId: '1:778603180925:ios:f9f7f311df0d15b387d214',
    messagingSenderId: '778603180925',
    projectId: 'buddy-app-5aa31',
    storageBucket: 'buddy-app-5aa31.firebasestorage.app',
    iosBundleId: 'com.example.buddyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4LhP8IZ_XtHD-iIPgTlB7y4ilgaJ1QnE',
    appId: '1:778603180925:web:8ddb5259aedfe5bc87d214',
    messagingSenderId: '778603180925',
    projectId: 'buddy-app-5aa31',
    authDomain: 'buddy-app-5aa31.firebaseapp.com',
    storageBucket: 'buddy-app-5aa31.firebasestorage.app',
    measurementId: 'G-JCREFV3609',
  );
}
